// Generated by CoffeeScript 1.7.1
(function() {
  this.s = io.connect('localhost');

  s.on('cast', function(data) {
    console.log("cast");
    return $('#tmp').append("<div>" + data + "</div>");
  });

}).call(this);
